version: '3.8'

volumes:
  pg_task:

services:
  TestTaskDB:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: TestTaskDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - pg_task:/var/lib/postgresql/data
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - TestTaskDB
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://TestTaskDB:5432/TestTaskDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345





